# Generated by Django 3.2.10 on 2021-12-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=50)),
                ('master_password', models.CharField(max_length=60)),
            ],
        ),
    ]
